float64[4] q        # subsystem_buffer{type: port; data_type: Eigen::Matrix<double,4,1>; includes: <Eigen/Dense>}

float64[4] dq       # subsystem_buffer{type: port; data_type: Eigen::Matrix<double,4,1>; includes: <Eigen/Dense>}

float64[4] max_p    # subsystem_buffer{type: port; data_type: Eigen::Matrix<double,4,1>; includes: <Eigen/Dense>}

float64[4] max_i    # subsystem_buffer{type: port; data_type: Eigen::Matrix<double,4,1>; includes: <Eigen/Dense>}

bool hold           # subsystem_buffer{type: port; data_type: bool }

