uint32 test

StatusArm rArm
bool rArm_valid

StatusArmFriRobot rArmFriRobot
StatusArmFriIntf rArmFriIntf

StatusArm lArm
bool lArm_valid

StatusArmFriRobot lArmFriRobot
StatusArmFriIntf lArmFriIntf

StatusHand rHand
bool rHand_valid

StatusHand lHand
bool lHand_valid

StatusFT rFt
bool rFt_valid

StatusFT lFt
bool lFt_valid

StatusMotor tMotor
bool tMotor_valid

StatusMotor hpMotor
bool hpMotor_valid

StatusMotor htMotor
bool htMotor_valid

barrett_hand_controller_msgs/BHPressureState rHand_p
bool rHand_p_valid

geometry_msgs/Wrench[3] lHand_f
bool lHand_f_valid

