float64[7] q                # subsystem_buffer{type: port; data_type: Eigen::Matrix<double,7,1>; includes: <Eigen/Dense>}
float64[7] dq               # subsystem_buffer{type: port; data_type: Eigen::Matrix<double,7,1>; includes: <Eigen/Dense>}
float64[7] t                # subsystem_buffer{type: port; data_type: Eigen::Matrix<double,7,1>; includes: <Eigen/Dense>}
float64[7] gt               # subsystem_buffer{type: port; data_type: Eigen::Matrix<double,7,1>; includes: <Eigen/Dense>}
geometry_msgs/Wrench w      # subsystem_buffer{type: port; data_type: geometry_msgs::Wrench }
float64[28] mmx             # subsystem_buffer{type: port; data_type: Eigen::Matrix<double,7,7>; includes: <Eigen/Dense>}

